= Contributing
ifndef::env-github[:icons: font]
ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

== Build

=== Java Support

Source code uses *Java 11* for development, however the API compatibility is restricted to *Java 8*.
This allows us to use the syntactical sugar advancements such as var, switch etc but still _support Java 8 projects_.
This is achieved with the use of https://github.com/bsideup/jabel[Jabel - javac compiler plugin].

- Development dependency: Java 11
- Runtime dependency: Java 8+

WARNING: Using Java 9+ APIs will result in compilation failure. See https://github.com/bsideup/jabel#how-jabel-works[how and why Jabel works] for more details.

=== Installation
Install artifacts to local repository -

[source,shell]
----
./mvnw install
----

== Releasing
GitHub Actions workflow is configured to use this same extension to version the project
and then use https://jreleaser.org/[JReleaser] to release this to https://search.maven.org/search?q=a:git-versioner-maven-extension[Maven Central].

_To trigger the release:_

*Install* the latest extension to local repository -

[source,shell]
----
./mvnw install
----

*Commit* using one of the link:README.adoc#_how_do_i_increment_version[Version Commit goals] -

.Example goal to increment patch
[source,shell]
----
 ./mvnw com.github.manikmagar:git-versioner-maven-plugin:V-LATEST-SNAPSHOT:commit-patch --non-recursive
----

.Example goal to increment minor
[source,shell]
----
 ./mvnw com.github.manikmagar:git-versioner-maven-plugin:V-LATEST-SNAPSHOT:commit-minor --non-recursive
----

*Verify* the new version by running plugin's `print` goal -

[source,shell]
----
 ./mvnw com.github.manikmagar:git-versioner-maven-plugin:V-LATEST-SNAPSHOT:print --non-recursive
----

In the output, you can look for version -

.Example version 0.6.0 print
[source,log]
----
...
[INFO] --- git-versioner-maven-plugin:V-LATEST-SNAPSHOT:print (default-cli) @ git-versioner-maven-parent ---
[INFO] VersionPatternStrategy [branch: main, version: 0.6.0, hash: 238bedfdff4e84f7c3964a494b91a76c4998287f]
....
----

*Tag* the new version by running plugin's `tag` goal -

[source,shell]
----
./mvnw com.github.manikmagar:git-versioner-maven-plugin:V-LATEST-SNAPSHOT:tag --non-recursive
----

This should create a tag with current verison.

.Example tag goal creating v0.6.0 tag
[source,log]
----
[INFO]
[INFO] --- git-versioner-maven-plugin:V-LATEST-SNAPSHOT:tag (default-cli) @ git-versioner-maven-parent ---
[INFO] Current Version: 0.6.0
[INFO] Tag Version 'v0.6.0' with message 'Release version 0.6.0'
[INFO] Created tag: 'refs/tags/v0.6.0@c95da362ef54a682f45b0a723aea609b3e980247'
[INFO] ------------------------------------------------------------------------
----

**Push** the release commit and tag

[source,shell]
----
# push branch commit
git push

tagName=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
# push the new tag
# example - git push origin v0.6.0
git push origin v$tagName
----

*Monitor* GitHub Actions Workflows for https://github.com/manikmagar/git-versioner-maven-plugin/actions/workflows/release.yml[release].

Once the pipeline succeeds, the new release should soon be available on