= Git Versioner Maven Plugin
ifndef::env-github[:icons: font]
ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:toc: macro

image:https://img.shields.io/github/release/manikmagar/git-versioner-maven-plugin.svg[Release,link=https://github.com/manikmagar/git-versioner-maven-plugin/releases]
image:https://github.com/manikmagar/git-versioner-maven-plugin/workflows/build/badge.svg[Build Status,link=https://github.com/manikmagar/git-versioner-maven-plugin/actions]
image:https://img.shields.io/github/license/manikmagar/git-versioner-maven-plugin[GitHub]

Generate the semver version using the git commit history and automatically set it to maven pom.

No more manually modifying the pom.xml to decide on the versions.
You continue developing and adding commits to your project.
When it is time to release, add a commit with a message containing
a specific version keyword and watch the magic happen.

toc::[]

== How does it work?
This plugin will look at all the commit history and compute the version number upto current commit.

This plugin supports generating Semantic Versions `x.y.z` format. When additional commits exist after the patch,
Git short hash for the latest commit is added as a build metadata - `x.y.z+shortHash`.

[#versionKeywords]
== What are version keywords?
Version keywords are the reserved words that will define which milestone of the release is this.

Plugin supports following keywords -

- `[major]` - A Major version milestone Eg. 1.0.0 -> 2.0.0
- `[minor]` - A Minor version milestone Eg. 1.1.0 -> 1.2.
- `[patch]` - A Patch version milestone Eg. 1.1.1 -> 1.1.2

== How to configure?
This is a maven build core extension that can -

- Participate in maven build lifecycle
- Automatically set the building project's version
- No explicit mojo executions needed to set the version
- Project's POM remain unchanged

To use as a maven build extension,

Create (or modify) `extensions.xml` file in `${project.baseDir}/.mvn/`
to have the following entry -

NOTE: The artifact id is *git-versioner-maven-_extension_*.

..mvn/extensions.xml
[source,xml]
----
<extensions xmlns="http://maven.apache.org/EXTENSIONS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/EXTENSIONS/1.0.0 https://maven.apache.org/xsd/core-extensions-1.0.0.xsd">
    <extension>
        <groupId>com.github.manikmagar</groupId>
        <artifactId>git-versioner-maven-extension</artifactId>
        <version>${latest-version-here}</version>
    </extension>

</extensions>
----

See an example test project at link:git-versioner-maven-extension/src/test/resources/project-with-extension/[].

With just that configuration, next time your project runs any maven goals, you should see version from this module.
Try running `mvn package` on your project.

=== Using as Maven Plugin

TIP: It is recommended to use as extension instead of plugin for version management

When used as a regular maven plugin:

- Project's POM needs to be configured with this plugin
- Plugin configurations can be used to customize the version behavior
- Requires a separate invocation of `git-version:set` or `initialize` goal
- Updates the project POM with calculated version

*Limitations:*

- Can not change the project version in ongoing execution

To use as a Maven plugin, add following configuration to your project's pom.xml -

NOTE: The artifact id is *git-versioner-maven-_plugin_*.

.Maven Plugin configuration
[source, xml]
----
<plugin>
    <groupId>com.github.manikmagar</groupId>
    <artifactId>git-versioner-maven-plugin</artifactId>
    <version>${git-versioner-maven-plugin.version}</version> // <1>
    <executions>
        <execution> // <2>
            <id>set-version</id>
            <goals>
                <goal>set</goal>
            </goals>
        </execution>
        <execution> // <3>
            <id>print-version</id>
            <goals>
                <goal>print</goal>
            </goals>
        </execution>
    </executions>
</plugin>
----

<1> Use the latest release version of this plugin.
<2> Add an execution for `set` goal. By default, it will be bound to maven _INITIALIZE_ phase.
<3> Optional. If you would like to print version details during _VALIDATE_ phase.

== How to start with a different version?
It is possible that your project is already released with a certain version.
In that case, you can configure the initial version to start counting versions from.

Assuming your application released version is v1.3.4, when appropriate initial version is set, the first version calculated by this extension/plugin will be -

- Major: *2.0.0*
- Minor: 1.*4.0*
- Patch: 1.3.*5*

=== Using as Maven Build Extension
When using as a build extension, you can add following properties to `.mvn/git-versioner-extension.properties` file -

.Example configuration for initial version for extension mode
[source,properties]
----
gv.initialVersion.major=1
gv.initialVersion.minor=3
gv.initialVersion.patch=4
----

=== Using as Maven Plugin
You can set a `versionConfig.initial` configuration block as below -

.Example configuration to start version from 1.3.4
[source,xml]
----
<plugin>
    <groupId>com.github.manikmagar</groupId>
    <artifactId>git-versioner-maven-plugin</artifactId>
    <version>${git-versioner-maven-plugin.version}</version>
    <configuration>
        <versionConfig>
            <initial>               // <1>
                <major>1</major>
                <minor>3</minor>
                <patch>4</patch>
            </initial>
        </versionConfig>
    </configuration>
    <executions>
        <execution>
            <id>set-version</id>
            <goals>
                <goal>set</goal>
            </goals>
        </execution>
    </executions>
</plugin>
----

== How do I increment version?
Now that you have plugin configured, you can continue with your regular development.

When it is time to increment version, you can add commits (preferably empty) with appropriate version keywords.

[source, shell]
----
git commit --allow-empty -m "chore: [<keyword>] release" // <1>
----

<1> where `<keyword>` can be one of these - major, minor, or patch.

== How to customize version keywords?
The default link:#versionKeywords[version keywords] `[major]`, `[minor]`, and `[patch]` can be customized by overriding the configuration.

=== Using as Maven Build Extension
When using as a build extension, you can add following properties to `.mvn/git-versioner-extension.properties` file -

.Example configuration for initial version for extension mode
[source,properties]
----
gv.keywords.majorKey=[BIG]
gv.keywords.minorKey=[SMALL]
gv.keywords.patchKey=[FIX]
----

=== Using as Maven Plugin

In this case, a `versionConfig.keywords` configuration block can be defined with required keywords.

.Example configuration with keywords overriding
[source,xml]
----
<plugin>
    <groupId>com.github.manikmagar</groupId>
    <artifactId>git-versioner-maven-plugin</artifactId>
    <version>0.1.0</version>
    <configuration>
        <versionConfig>
            <initial>
                <major>1</major>
                <minor>3</minor>
                <patch>4</patch>
            </initial>
            <keywords>              // <1>
                <majorKey>[BIG]</majorKey>
                <minorKey>[SMALL]</minorKey>
                <patchKey>[FIX]</patchKey>
            </keywords>
        </versionConfig>
    </configuration>
    <executions>
        <execution>
            <id>set-version</id>
            <goals>
                <goal>set</goal>
            </goals>
        </execution>
    </executions>
</plugin>
----

<1> Override one or all version keywords.

== Maven Plugin-only features

When used a maven plugin, few additional feature goals are available.
Even if the extension is being used, you can still add a maven plugin entry to leverage following goals.

WARNING: Maven Extension DOES NOT use configuration element from plugin, if exist.

TIP: DO NOT combine using extension as well as maven plugin `set` goal. Extension mode is recommended for versioning.

=== Can I access generated version properties?
When using as an extension, following properties are made available as *Maven properties* during build cycle -

.Example of Injected maven properties (demo values)
[source, properties]
----
git-versioner.commitNumber=0
git-versioner.major=0
git-versioner.minor=0
git-versioner.patch=1
git-versioner.version=0.0.1
git.branch=main
git.hash=67550ad6a64fe4e09bf9e36891c09b2f7bdc52f9
git.hash.short=67550ad
----

You may use these properties in maven pom file, for example as `${git.branch}` to access git branch name.


=== How to create Git tags?
.[Plugin-only feature]
You can use `git-versioner:tag` goal to create a git tag for current version in local git repository.

NOTE: This does not push tag to remote repository.

.Git Tag Goal with default configuration parameters
[source, xml]
----
<plugin>
    <groupId>com.github.manikmagar</groupId>
    <artifactId>git-versioner-maven-plugin</artifactId>
    <executions>
      <execution>
        <id>tag</id>
        <goals>
          <goal>tag</goal>
        </goals>
        <configuration>
          <failWhenTagExist>true</failWhenTagExist> // <1>
          <tagNamePattern>v%v</tagNamePattern>  // <2>
          <tagMessagePattern>Release version %v</tagMessagePattern> // <3>
        </configuration>
      </execution>
    </executions>
</plugin>
----

<1> If set to not fail, it will just log warning and skip tag creation.
<2> Tag name pattern to use. Default `v%v` will result in tags like `v1.2.3`.
<3> Tag message pattern to use. Default `Release version %v` will add tag message like `Release version 1.2.3`.

== Acknowledgement
This is inspired from Gradle plugin https://github.com/toolebox-io/gradle-git-versioner[toolebox-io/gradle-git-versioner] that I have been using for my Gradle projects. This maven plugin is my attempt to get those auto-version capabilities into my Maven builds.